language: php
php:
  - 5.4
  - 5.6
  - 7.1
  - hhvm

before_script:
  - composer self-update
  - composer install --dev

# Commands you want to run that will verify your build.
script: phpunit --bootstrap src/ngfw/Recipe.php tests/RecipeTest.php
